# Generated by Django 4.1.1 on 2022-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_belonged',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='user_belonged',
        ),
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(to='core.message'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedules',
            field=models.ManyToManyField(to='core.schedule'),
        ),
    ]
