# Generated by Django 4.1.1 on 2022-10-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_message_user_belonged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_belonged',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user_belonged',
        ),
    ]
