# Generated by Django 4.1.1 on 2022-10-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_message_user_belonged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
